// AUTO-GENERATED by electron/main.js — exposes the backend WS URL and a
// report() bridge to the renderer (contextIsolation: true).
const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('M3V', {
  wsUrl: "ws://127.0.0.1:63197",
  report: (payload) => ipcRenderer.send('m3v-report', payload),
});
